[workspace]
resolver = '2'

members = [
  "models/perceiver",
  "models/bare_attention",
  "models/nutrition-viewer",
  "applications/nutrition-labels",
  "data/synthetic-nutrition-labels",

#"common/transformers",
]
