[package]
name = "bare_attention"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { version = "0.10.0", features = ["wgpu"] }
serde = "1.0.192"

[dev-dependencies]
anyhow = "1.0.75"
